[package]
name = "gir"
version = "0.1.0"
authors = ["Jake Goldsborough <jake.goldsborough@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.9"
rust-ini = "0.15.2"
